load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cel2ansisql",
    srcs = ["cel2ansisql.go"],
    importpath = "github.com/aep-dev/aep-monorepo/aepc/pkg/cel2ansisql",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_google_cel_go//cel:go_default_library",
        "@org_golang_google_genproto_googleapis_api//expr/v1alpha1",
    ],
)

go_test(
    name = "cel2ansisql_test",
    srcs = ["cel2ansisql_test.go"],
    embed = [":cel2ansisql"],
    deps = ["@com_github_google_cel_go//cel:go_default_library"],
)
