load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "aep0142",
    srcs = [
        "aep0142.go",
        "time_field_names.go",
        "time_field_type.go",
    ],
    importpath = "github.com/aep-dev/aep-monorepo/api-linter/rules/aep0142",
    visibility = ["//visibility:public"],
    deps = [
        "//api-linter/lint",
        "//api-linter/locations",
        "//api-linter/rules/internal/utils",
        "@com_github_jhump_protoreflect//desc",
        "@org_bitbucket_creachadair_stringset//:stringset",
    ],
)

go_test(
    name = "aep0142_test",
    srcs = [
        "aep0142_test.go",
        "time_field_names_test.go",
        "time_field_type_test.go",
    ],
    embed = [":aep0142"],
    deps = [
        "//api-linter/lint",
        "//api-linter/rules/internal/testutils",
    ],
)
