load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "utils",
    srcs = [
        "casing.go",
        "comments.go",
        "common_lints.go",
        "common_proto.go",
        "declarative_friendly.go",
        "extension.go",
        "find.go",
        "http.go",
        "message.go",
        "method.go",
        "resource.go",
        "string_pluralize.go",
        "type_name.go",
    ],
    importpath = "github.com/aep-dev/aep-monorepo/api-linter/rules/internal/utils",
    visibility = ["//api-linter/rules:__subpackages__"],
    deps = [
        "//api-linter/lint",
        "//api-linter/locations",
        "@build_buf_gen_go_aep_api_protocolbuffers_go//aep/api",
        "@com_github_gertd_go_pluralize//:go-pluralize",
        "@com_github_jhump_protoreflect//desc",
        "@com_github_jhump_protoreflect//desc/builder",
        "@com_github_stoewer_go_strcase//:go-strcase",
        "@com_google_cloud_go_longrunning//autogen/longrunningpb",
        "@org_bitbucket_creachadair_stringset//:stringset",
        "@org_golang_google_genproto_googleapis_api//annotations",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/descriptorpb",
    ],
)

go_test(
    name = "utils_test",
    srcs = [
        "casing_test.go",
        "comments_test.go",
        "common_lints_test.go",
        "common_proto_test.go",
        "declarative_friendly_test.go",
        "extension_test.go",
        "find_test.go",
        "http_test.go",
        "message_test.go",
        "method_test.go",
        "resource_test.go",
        "string_pluralize_test.go",
        "type_name_test.go",
    ],
    embed = [":utils"],
    deps = [
        "//api-linter/rules/internal/testutils",
        "@build_buf_gen_go_aep_api_protocolbuffers_go//aep/api",
        "@com_github_google_go_cmp//cmp",
        "@com_github_jhump_protoreflect//desc/builder",
        "@org_bitbucket_creachadair_stringset//:stringset",
        "@org_golang_google_genproto_googleapis_api//annotations",
        "@org_golang_google_protobuf//proto",
    ],
)
