load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "aep0133",
    srcs = [
        "aep0133.go",
        "http_body.go",
        "http_method.go",
        "http_uri_parent.go",
        "http_uri_resource.go",
        "method_signature.go",
        "request_id_field.go",
        "request_message_name.go",
        "request_parent_behavior.go",
        "request_parent_field.go",
        "request_parent_required.go",
        "request_required_fields.go",
        "request_resource_behavior.go",
        "request_resource_field.go",
        "request_unknown_fields.go",
        "resource_reference_type.go",
        "response_message_name.go",
        "synonyms.go",
    ],
    importpath = "github.com/aep-dev/aep-monorepo/api-linter/rules/aep0133",
    visibility = ["//visibility:public"],
    deps = [
        "//api-linter/lint",
        "//api-linter/locations",
        "//api-linter/rules/internal/utils",
        "@com_github_jhump_protoreflect//desc",
        "@com_github_jhump_protoreflect//desc/builder",
        "@com_github_stoewer_go_strcase//:go-strcase",
        "@org_bitbucket_creachadair_stringset//:stringset",
    ],
)

go_test(
    name = "aep0133_test",
    srcs = [
        "aep0133_test.go",
        "http_body_test.go",
        "http_method_test.go",
        "http_uri_parent_test.go",
        "http_uri_resource_test.go",
        "method_signature_test.go",
        "request_id_field_test.go",
        "request_message_name_test.go",
        "request_parent_behavior_test.go",
        "request_parent_field_test.go",
        "request_parent_required_test.go",
        "request_required_fields_test.go",
        "request_resource_behavior_test.go",
        "request_resource_field_test.go",
        "request_unknown_fields_test.go",
        "resource_reference_type_test.go",
        "response_message_name_test.go",
        "synonyms_test.go",
    ],
    embed = [":aep0133"],
    deps = [
        "//api-linter/lint",
        "//api-linter/rules/internal/testutils",
        "@com_github_jhump_protoreflect//desc",
        "@com_github_jhump_protoreflect//desc/builder",
    ],
)
