name: aep-lib-go CI

on:
  push:
    branches: [main]
    paths:
      - 'aep-lib-go/**'
      - '.github/workflows/aep-lib-go-*.yml'
  pull_request:
    branches: [main]
    paths:
      - 'aep-lib-go/**'
      - '.github/workflows/aep-lib-go-*.yml'

jobs:
  test:
    name: Run aep-lib-go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Run tests
        run: bazel test //aep-lib-go/...
