name: aep-e2e-validator CI

on:
  push:
    branches: [main]
    paths:
      - 'aep-e2e-validator/**'
      - '.github/workflows/aep-e2e-validator-*.yml'
  pull_request:
    branches: [main]
    paths:
      - 'aep-e2e-validator/**'
      - '.github/workflows/aep-e2e-validator-*.yml'

jobs:
  test:
    name: Run aep-e2e-validator Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Run tests
        run: bazel test //aep-e2e-validator/...
