name: aepcli CI

on:
  push:
    branches: [main]
    paths:
      - 'aepcli/**'
      - '.github/workflows/aepcli-*.yml'
  pull_request:
    branches: [main]
    paths:
      - 'aepcli/**'
      - '.github/workflows/aepcli-*.yml'

jobs:
  test:
    name: Run aepcli Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Run tests
        run: bazel test //aepcli/...
